In [28]:
import numpy as np
import pandas as pd

data = pd.read_csv('/kaggle/input/digit-recognizer/train.csv')

In [29]:
data = np.array(data)

m, n = data.shape
np.random.shuffle(data)

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255
_,m_train = X_train.shape

In [30]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10 ,10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    exp_Z = np.exp(Z - np.max(Z, axis=0, keepdims=True)) 
    return exp_Z / np.sum(exp_Z, axis=0, keepdims=True)


def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b1
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2



def ReLU_deriv(Z):
    return Z > 0

def one_hot(Y):  #This is plagiarized. I couldn't do it. It was hard.
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y


def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2



def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2  
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2

In [31]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size


def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [32]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 500)

Iteration:  0
[1 8 0 ... 0 0 0] [1 7 8 ... 0 9 9]
0.09907317073170732
Iteration:  10
[1 8 9 ... 5 2 4] [1 7 8 ... 0 9 9]
0.23692682926829267
Iteration:  20
[1 7 7 ... 0 9 4] [1 7 8 ... 0 9 9]
0.3385365853658537
Iteration:  30
[1 7 7 ... 0 9 4] [1 7 8 ... 0 9 9]
0.3933170731707317
Iteration:  40
[1 7 2 ... 0 9 4] [1 7 8 ... 0 9 9]
0.4430731707317073
Iteration:  50
[1 7 2 ... 0 9 4] [1 7 8 ... 0 9 9]
0.4898048780487805
Iteration:  60
[1 7 2 ... 0 9 4] [1 7 8 ... 0 9 9]
0.5329024390243903
Iteration:  70
[1 7 8 ... 0 9 4] [1 7 8 ... 0 9 9]
0.5703414634146341
Iteration:  80
[1 7 8 ... 0 9 4] [1 7 8 ... 0 9 9]
0.6013658536585366
Iteration:  90
[1 7 8 ... 0 9 4] [1 7 8 ... 0 9 9]
0.6285121951219512
Iteration:  100
[1 7 8 ... 0 9 4] [1 7 8 ... 0 9 9]
0.6523170731707317
Iteration:  110
[1 7 8 ... 0 9 4] [1 7 8 ... 0 9 9]
0.6718536585365854
Iteration:  120
[1 7 8 ... 0 9 4] [1 7 8 ... 0 9 9]
0.6890975609756097
Iteration:  130
[1 7 8 ... 0 9 4] [1 7 8 ... 0 9 9]
0.7035365853658536
Iteration:  140